packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    majorVersion: 9.3.0

targets:
  App:
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
    sources:
      - path: ./Analytics
        name: Analytics
        group: Features